name: Build_MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, task0, task00, task1, task01, task2, task02, task3, task03, task5, task05, task6, task06, task7, task07, task8, task08, task9, task09]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: macos-latest-latest

    steps:
    - name: Show Xcode version
      run: xcodebuild -version    

    - uses: actions/checkout@v2

    - name: install glfw
      run: |
        brew install glfw

    - name: get eigen
      run: |
        git submodule update --init -- external/eigen

    - name: build
      run: |
        cmake .
        cmake --build .